# Automations

automation:

# Automatically turn OFF Back light based on time & sensor input_boolean

  - alias: Back Light Off
    trigger:
      - platform: state
        entity_id: binary_sensor.back_pir
        to: 'off'
        for: '00:07:00'
      - platform: state
        entity_id: binary_sensor.back_door
        to: 'off'
        for: '00:07:00'
    condition:
      - condition: state
        entity_id: light.back
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.back

# Automatically turn ON Back light based on time & sensor input_boolean

  - alias: Light Back Auto On 10 When Dark
    trigger:
      - platform: state
        entity_id: binary_sensor.back_door
        to: 'on'
      - platform: state
        entity_id: binary_sensor.back_pir
        to: 'on'
    condition:
      condition: numeric_state
      entity_id: sensor.back_luminance
      below: 40
    action:
      - service: light.turn_on
        entity_id: light.back
