# Automations

automation:

# Automatically turn OFF Bathroom light based on time & sensor input_boolean

  - alias: Bathroom Light Auto Off
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_pir
        to: "off"
        for: "00:35:00" 
    condition:
      - condition: state
        entity_id: light.bathroom
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.bathroom_humidity
        below: 90
    action:
      - service: light.turn_off
        entity_id: light.bathroom
