# InfluxDB, Recorder & Logbook Settings

logbook:
  exclude:
    entities:
      - automation.front_porch_camera_motion_trigger_person_detection
      - automation.front_porch_camera_motion_timer
      - automation.front_porch_person_timer
      - sensor.kitchen_battery
      - sensor.time
      - sensor.date
      - sensor.date_time
      - sensor.back_door_sourcenodeid
      - sensor.back_multi_sourcenodeid
      - sensor.bathroom_pir_sourcenodeid
      - sensor.bedroom_closet_multi_sourcenodeid
      - sensor.bedroom_pir_sourcenodeid
      - sensor.front_door_sourcenodeid
      - sensor.front_multi_sourcenodeid
      - sensor.hallway_pir_sourcenodeid
      - sensor.laundry_pir_sourcenodeid
      - sensor.main_pir_sourcenodeid
      - sensor.back_door_alarm_type
      - sensor.back_multi_alarm_type
      - sensor.bathroom_pir_alarm_type
      - sensor.bedroom_closet_multi_alarm_type
      - sensor.bedroom_pir_alarm_type
      - sensor.front_door_alarm_type
      - sensor.front_multi_alarm_type
      - sensor.hallway_pir_alarm_type
      - sensor.laundry_pir_alarm_type
      - sensor.main_pir_alarm_type
      - sensor.back_door_alarm_level
      - sensor.back_multi_alarm_level
      - sensor.bathroom_pir_alarm_level
      - sensor.bedroom_closet_alarm_level
      - sensor.bedroom_pir_alarm_level
      - sensor.front_door_alarm_level
      - sensor.front_multi_alarm_level
      - sensor.hallway_pir_alarm_level
      - sensor.laundry_pir_alarm_level
      - sensor.main_pir_alarm_level
      - switch.bathroom
      - switch.hallway
      - sensor.hallway_thermostat_indicator
      - sensor.bedroom_closet_multi_burglar
      - sensor.back_multi_burglar
      - sensor.bedroom_closet_multi_alarm_level
      - sensor.bedroom_closet_multi_alarm_level
      - sensor.back_door_power_management
      - sensor.bathroom_pir_power_management
      - sensor.bedroom_pir_power_management
      - sensor.front_door_power_management
      - sensor.hallway_pir_power_management
      - sensor.laundry_pir_power_management
      - sensor.main_pir_power_management
      - sensor.front_multi_burglar
      - sensor.bedroom_pir_burglar
      - sensor.front_door_access_control
      - sensor.back_door_sensor_access_control
      - sensor.back_door_burglar
      - sensor.bathroom_pir_burglar
      - sensor.bedroom_pir_burglar
      - sensor.front_door_burglar
      - sensor.hallway_pir_burglar
      - sensor.laundry_pir_burglar
      - sensor.main_pir_burglar

recorder:
  db_url: !secret db_url
  purge_keep_days: 7
  exclude:
    entities:
      - automation.front_porch_camera_motion_trigger_person_detection
      - automation.front_porch_camera_motion_timer
      - automation.front_porch_person_timer
      - sensor.kitchen_battery
      - sensor.time
      - sensor.date
      - sensor.date_time
      - sensor.back_door_sourcenodeid
      - sensor.back_multi_sourcenodeid
      - sensor.bathroom_pir_sourcenodeid
      - sensor.bedroom_closet_multi_sourcenodeid
      - sensor.bedroom_pir_sourcenodeid
      - sensor.front_door_sourcenodeid
      - sensor.front_multi_sourcenodeid
      - sensor.hallway_pir_sourcenodeid
      - sensor.laundry_pir_sourcenodeid
      - sensor.main_pir_sourcenodeid
      - sensor.back_door_alarm_type
      - sensor.back_multi_alarm_type
      - sensor.bathroom_pir_alarm_type
      - sensor.bedroom_closet_multi_alarm_type
      - sensor.bedroom_pir_alarm_type
      - sensor.front_door_alarm_type
      - sensor.front_multi_alarm_type
      - sensor.hallway_pir_alarm_type
      - sensor.laundry_pir_alarm_type
      - sensor.main_pir_alarm_type
      - sensor.back_door_alarm_level
      - sensor.back_multi_alarm_level
      - sensor.bathroom_pir_alarm_level
      - sensor.bedroom_closet_alarm_level
      - sensor.bedroom_pir_alarm_level
      - sensor.front_door_alarm_level
      - sensor.front_multi_alarm_level
      - sensor.hallway_pir_alarm_level
      - sensor.laundry_pir_alarm_level
      - sensor.main_pir_alarm_level
      - switch.bathroom
      - switch.hallway
      - sensor.hallway_thermostat_indicator
      - sensor.bedroom_closet_multi_burglar
      - sensor.back_multi_burglar
      - sensor.bedroom_closet_multi_alarm_level
      - sensor.bedroom_closet_multi_alarm_level
      - sensor.back_door_power_management
      - sensor.bathroom_pir_power_management
      - sensor.bedroom_pir_power_management
      - sensor.front_door_power_management
      - sensor.hallway_pir_power_management
      - sensor.laundry_pir_power_management
      - sensor.main_pir_power_management
      - sensor.front_multi_burglar
      - sensor.bedroom_pir_burglar
      - sensor.front_door_access_control
      - sensor.back_door_sensor_access_control
      - sensor.back_door_burglar
      - sensor.bathroom_pir_burglar
      - sensor.bedroom_pir_burglar
      - sensor.front_door_burglar
      - sensor.hallway_pir_burglar
      - sensor.laundry_pir_burglar
      - sensor.main_pir_burglar

influxdb:
  host: !secret inno_host
  database: !secret inno_user
  username: !secret inno_user
  password: !secret inno_pass
  max_retries: 3
  default_measurement: state
  exclude:
    entities:
      - automation.front_porch_camera_motion_trigger_person_detection
      - automation.front_porch_camera_motion_timer
      - automation.front_porch_person_timer
      - sensor.kitchen_battery
      - sensor.time
      - sensor.date
      - sensor.date_time
      - sensor.back_door_sourcenodeid
      - sensor.back_multi_sourcenodeid
      - sensor.bathroom_pir_sourcenodeid
      - sensor.bedroom_closet_multi_sourcenodeid
      - sensor.bedroom_pir_sourcenodeid
      - sensor.front_door_sourcenodeid
      - sensor.front_multi_sourcenodeid
      - sensor.hallway_pir_sourcenodeid
      - sensor.laundry_pir_sourcenodeid
      - sensor.main_pir_sourcenodeid
      - sensor.back_door_alarm_type
      - sensor.back_multi_alarm_type
      - sensor.bathroom_pir_alarm_type
      - sensor.bedroom_closet_multi_alarm_type
      - sensor.bedroom_pir_alarm_type
      - sensor.front_door_alarm_type
      - sensor.front_multi_alarm_type
      - sensor.hallway_pir_alarm_type
      - sensor.laundry_pir_alarm_type
      - sensor.main_pir_alarm_type
      - sensor.back_door_alarm_level
      - sensor.back_multi_alarm_level
      - sensor.bathroom_pir_alarm_level
      - sensor.bedroom_closet_alarm_level
      - sensor.bedroom_pir_alarm_level
      - sensor.front_door_alarm_level
      - sensor.front_multi_alarm_level
      - sensor.hallway_pir_alarm_level
      - sensor.laundry_pir_alarm_level
      - sensor.main_pir_alarm_level
      - switch.bathroom
      - switch.hallway
      - sensor.hallway_thermostat_indicator
      - sensor.bedroom_closet_multi_burglar
      - sensor.back_multi_burglar
      - sensor.bedroom_closet_multi_alarm_level
      - sensor.bedroom_closet_multi_alarm_level
      - sensor.back_door_power_management
      - sensor.bathroom_pir_power_management
      - sensor.bedroom_pir_power_management
      - sensor.front_door_power_management
      - sensor.hallway_pir_power_management
      - sensor.laundry_pir_power_management
      - sensor.main_pir_power_management
      - sensor.front_multi_burglar
      - sensor.bedroom_pir_burglar
      - sensor.front_door_access_control
      - sensor.back_door_sensor_access_control
      - sensor.back_door_burglar
      - sensor.bathroom_pir_burglar
      - sensor.bedroom_pir_burglar
      - sensor.front_door_burglar
      - sensor.hallway_pir_burglar
      - sensor.laundry_pir_burglar
      - sensor.main_pir_burglar
