# Automations

automation:

# Automatically turn OFF Hallway light based on time & sensor input_boolean

  - alias: Hallway Light Auto Off
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_pir
        to: "off"
        for: "00:00:30" 
    condition:
      - condition: state
        entity_id: light.hallway
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.hallway
