input_select:
  intel_nuc_led:
    name: Intel NUC Ring-LED
    options:
      - green
      - yellow
      - red
      - red_flash
automation:
  - alias: Nuc Led Red Flash
    trigger:
      - platform: state
        entity_id: input_select.intel_nuc_led
        to: red_flash
    action:
      - service: shell_command.nuc_led_red_flash
  - alias: Nuc Led Green Late
    trigger:
      - platform: state
        entity_id: input_select.intel_nuc_led
        to: green
    condition:
      condition: time
      after: '22:00:00'
      before: '07:00:00'
    action:
      - service: shell_command.nuc_led_off
  - alias: Nuc Led Green
    trigger:
      - platform: state
        entity_id: input_select.intel_nuc_led
        to: green
    condition:
      condition: time
      after: '07:00:00'
      before: '22:00:00'
    action:
      - service: shell_command.nuc_led_green
  - alias: Nuc Ring Led Off
    trigger:
      - platform: time
        at: '22:00:00'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ not is_state('input_select.intel_nuc_led', 'red') }}"
        - condition: template
          value_template: "{{ not is_state('input_select.intel_nuc_led', 'red_flash') }}"
    action:
      - service: shell_command.nuc_led_off
  - alias: Nuc Power Led Off
    trigger:
      - platform: time
        at: '22:00:00'
    action:
      - service: shell_command.nuc_power_led_off
  - alias: Nuc Ring Led On
    trigger:
      - platform: time
        at: 07:00:00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.intel_nuc_led
          state: green
    action:
      - service: shell_command.nuc_led_green
  - alias: Nuc Power Led On
    trigger:
      - platform: time
        at: '07:00:00'
    action:
      - service: shell_command.nuc_power_led_blue
  - alias: Nuc Led Red
    trigger:
      - platform: state
        entity_id: input_select.intel_nuc_led
        to: red
    action:
      - service: shell_command.nuc_led_red
  - alias: Nuc Led Yellow Late
    trigger:
      - platform: state
        entity_id: input_select.intel_nuc_led
        to: yellow
    condition:
      condition: time
      after: '22:00:00'
      before: '07:00:00'
    action:
      - service: shell_command.nuc_led_off
  - alias: Nuc Led Yellow
    trigger:
      - platform: state
        entity_id: input_select.intel_nuc_led
        to: yellow
    condition:
      condition: time
      after: '07:00:00'
      before: '22:00:00'
    action:
      - service: shell_command.nuc_led_yellow
shell_command:
  nuc_led_green: !secret shell_nuc_led_green
  nuc_led_yellow: !secret shell_nuc_led_yellow
  nuc_led_red: !secret shell_nuc_led_red
  nuc_led_pink: !secret shell_nuc_led_pink
  nuc_led_cyan: !secret shell_nuc_led_cyan
  nuc_led_white: !secret shell_nuc_led_white
  nuc_power_led_blue: !secret shell_nuc_power_led_blue
  nuc_power_led_amber: !secret shell_nuc_power_led_amber
  nuc_power_led_off: !secret shell_nuc_power_led_off
  nuc_led_red_flash: !secret shell_nuc_led_red_flash
  nuc_led_off: !secret shell_nuc_led_off