automation:

  - alias: Kitchen Switch Scene - Main Lights Off
    trigger:
      - event_data:
          entity_id: zwave.kitchen_light
          scene_data: 3
          scene_id: 1
        event_type: zwave.scene_activated
        platform: event
    condition: []
    action:
      - data:
          entity_id:
          - light.main_lights
        service: light.turn_off

  - alias: Light Kitchen Switch - Main Lights On
    trigger:
      - event_data:
          entity_id: zwave.kitchen_light
          scene_data: 3
          scene_id: 2
        event_type: zwave.scene_activated
        platform: event
    condition: []
    action:
      - data:
          entity_id: light.main_rgb
        service: light.turn_off
      - data:
          entity_id:
          - light.main
          - light.kitchen
          brightness: 255
        service: light.turn_on