# Automations

automation:

# Automatically turn OFF Kitchen light based on time & sensor input_boolean

  - alias: Kitchen Auto-Off Day
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: "off"
        for:
          minutes: 3
    condition:
      condition: and
      conditions:
        - condition: state
          state: 'on'
          entity_id: light.kitchen
        - condition: time
          after: '07:00:00'
          before: '16:00:00'
        # - condition: state
        #   entity_id: binary_sensor.desktop
        #   state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.kitchen

  - alias: Kitchen Auto-Off Night
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: "off"
        for:
          minutes: 1
    condition:
      condition: and
      conditions:
        - condition: state
          state: 'on'
          entity_id: light.kitchen
        - condition: state
          entity_id: binary_sensor.desktop
          state: 'off'
        - condition: time
          after: '16:00:00'
          before: '07:00:00'
    action:
      - service: light.turn_off
        entity_id: light.kitchen

# Automatically turn ON Kitchen light based on time & sensor input_boolean

  - alias: Kitchen Auto On 1 Midnight
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: 'off'
        - condition: time
          after: '00:00:00'
          before: '02:00:00'
    action:
      - service: light.turn_on
        entity_id: light.kitchen
        data:
          brightness_pct: 40

  - alias: Kitchen Auto On 2 AM
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: 'off'
        - condition: time
          after: '01:00:00'
          before: '02:00:00'
    action:
      - service: light.turn_on
        entity_id: light.kitchen
        data:
          brightness_pct: 20

  - alias: Kitchen Auto On 4 Dawn
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: 'off'
        - condition: time
          after: '05:00:00'
          before: '10:00:00'
        - condition: numeric_state
          entity_id: sensor.front_luminance
          above: 0
          below: 100
    action:
      - service: light.turn_on
        entity_id: light.kitchen
        data:
          brightness_pct: 50 

  - alias: Kitchen Auto On 5 Morning
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: 'off'
        - condition: numeric_state
          entity_id: sensor.front_luminance
          above: 100
        - condition: time
          after: '05:00:00'
          before: '10:00:00'
    action:
      - service: light.turn_on
        entity_id: light.kitchen
        data:
          brightness_pct: 100

  - alias: Kitchen Auto On 6 Day
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: 'off'
        - condition: time
          after: '10:00:00'
          before: '16:00:00'
    action:
      - service: light.turn_on
        entity_id: light.kitchen
        data:
          brightness_pct: 100

  - alias: Kitchen auto on 10 eve
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: 'off'
        - condition: numeric_state
          entity_id: sensor.front_luminance
          below: 60
        - condition: time
          after: "16:00:00"
          before: "19:30:00"
    action:
      - service: light.turn_on
        entity_id: light.kitchen
        data:
          brightness_pct: 100

  - alias: Kitchen Auto On 11 Night
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: 'off'
        - condition: time
          after: '19:30:00'
          before: '20:30:00'
    action:
      - service: light.turn_on
        entity_id: light.kitchen
        data:
          brightness_pct: 90

  - alias: Kitchen Auto On 11.5 Night2
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: 'off'
        - condition: time
          after: '20:30:00'
          before: '21:30:00'
    action:
      - service: light.turn_on
        entity_id: light.kitchen
        data:
          brightness_pct: 75

  - alias: Kitchen Auto On 12 Late
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: 'off'
        - condition: time
          after: '21:30:00'
          before: '22:30:00'
    action:
      - service: light.turn_on
        entity_id: light.kitchen
        data:
          brightness_pct: 55

  - alias: Kitchen Auto On 13 Later
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: 'off'
        - condition: time
          after: '22:30:00'
          before: '23:30:00'
    action:
      - service: light.turn_on
        entity_id: light.kitchen
        data:
          brightness_pct: 40

  - alias: Kitchen Auto On 14 almost midnight
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: 'off'
        - condition: time
          after: '23:30:00'
          before: '00:00:00'
    action:
      - service: light.turn_on
        entity_id: light.kitchen
        data:
          brightness_pct: 25

  # Kitchen Dimmer Scene Control
  - alias: Kitchen Switch Scene - Main Lights Off
    trigger:
      - event_data:
          entity_id: zwave.kitchen_light
          scene_data: 3
          scene_id: 1
        event_type: zwave.scene_activated
        platform: event
    condition: []
    action:
      - data:
          entity_id:
          - light.main_lights
        service: light.turn_off

  - alias: Light Kitchen Switch - Main Lights On
    trigger:
      - event_data:
          entity_id: zwave.kitchen_light
          scene_data: 3
          scene_id: 2
        event_type: zwave.scene_activated
        platform: event
    condition: []
    action:
      - data:
          entity_id: light.main_rgb
        service: light.turn_off
      - data:
          entity_id:
          - light.main
          - light.kitchen
          brightness: 255
        service: light.turn_on

# Time Based Automations

  - alias: Time kitchen 1 midnight
    description: Adjust Kitchen light at midnight when its on
    trigger:
    - at: '00:00:00'
      platform: time
    condition:
    - condition: state
      entity_id: light.kitchen
      state: 'on'
    action:
    - data:
        entity_id: light.kitchen
        brightness_pct: 10
      service: light.turn_on

  - alias: Time kitchen 2 AM
    description: Adjust Kitchen light at AM when its on
    trigger:
    - at: '01:00:00'
      platform: time
    condition:
    - condition: state
      entity_id: light.kitchen
      state: 'on'
    action:
    - data:
        entity_id: light.kitchen
        brightness_pct: 5
      service: light.turn_on

  - alias: Time kitchen 4 dawn
    description: Adjust Kitchen light at dawn when its on
    trigger:
      platform: numeric_state
      entity_id: sensor.front_luminance
      above: 0
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: 'on'
        - condition: time
          after: '02:00:00'
          before: '07:00:00'
    action:
    - data:
        entity_id: light.kitchen
        brightness_pct: 50
      service: light.turn_on

  - alias: Time kitchen 11 night
    description: Adjust Kitchen light at night when its on
    trigger:
    - at: '19:30:00'
      platform: time
    condition:
    - condition: state
      entity_id: light.kitchen
      state: 'on'
    action:
    - data:
        entity_id: light.kitchen
        brightness_pct: 90
      service: light.turn_on

  - alias: Time kitchen 11.5 night2
    description: Adjust Kitchen light at night2 when its on
    trigger:
    - at: '20:30:00'
      platform: time
    condition:
    - condition: state
      entity_id: light.kitchen
      state: 'on'
    action:
    - data:
        entity_id: light.kitchen
        brightness_pct: 75
      service: light.turn_on

  - alias: Time kitchen 12 late
    description: Adjust Kitchen light at late when its on
    trigger:
    - at: '21:30:00'
      platform: time
    condition:
    - condition: state
      entity_id: light.kitchen
      state: 'on'
    action:
    - data:
        entity_id: light.kitchen
        brightness_pct: 55
      service: light.turn_on

  - alias: Time kitchen 13 later
    description: Adjust Kitchen light at later when its on
    trigger:
    - at: '22:30:00'
      platform: time
    condition:
    - condition: state
      entity_id: light.kitchen
      state: 'on'
    action:
    - data:
        entity_id: light.kitchen
        brightness_pct: 40
      service: light.turn_on

  - alias: Time kitchen 14 almost midnight
    description: Adjust Kitchen light at almost midnight when its on
    trigger:
    - at: '23:30:00'
      platform: time
    condition:
    - condition: state
      entity_id: light.kitchen
      state: 'on'
    action:
    - data:
        entity_id: light.kitchen
        brightness_pct: 25
      service: light.turn_on
