automation:

  - alias: Main Dimmer Off - Sync
    trigger:
      - platform: state
        entity_id: light.main_dimmer
        to: 'off'
    condition:
      - condition: state
        entity_id: light.main_rgbw
        state: 'on'
    action:
      - data:
          entity_id: light.main_rgbw
        service: light.turn_off

  - alias: Main Dimmer On - Sync
    trigger:
      - platform: state
        entity_id: light.main_dimmer
        to: 'on'
    condition:
      - condition: state
        entity_id: light.main_rgbw
        state: 'off'
    action:
      - data:
          entity_id: light.main_rgbw
          brightness: 255
        service: light.turn_on
      - data:
          entity_id: light.main_rgbw
        service: zwave.refresh_entity