automation:
  - alias: Cube Blue
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:15:8d:00:02:9a:92:92'
        command: 'flip'
        args:
          - activated_face: 1
    action:
      - service: light.turn_on
        entity_id: light.main
        data:
          color_name: 'blue'
  - alias: Cube Green
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:15:8d:00:02:9a:92:92'
        command: 'flip'
        args:
          - activated_face: 2
    action:
      - service: light.turn_on
        entity_id: light.main
        data:
          color_name: 'green'
  - alias: Cube Off
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:15:8d:00:02:9a:92:92'
        command: 'shake'
    action:
      - service: light.turn_off
        entity_id: light.main
  - alias: Cube Orange
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:15:8d:00:02:9a:92:92'
        command: 'flip'
        args:
          - activated_face: 3
    action:
      - service: light.turn_on
        entity_id: light.main
        data:
          color_name: 'orange'
  - alias: Cube Purple
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:15:8d:00:02:9a:92:92'
        command: 'flip'
        args:
          - activated_face: 4
    action:
      - service: light.turn_on
        entity_id: light.main
        data:
          color_name: 'purple'
  - alias: Cube Red
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:15:8d:00:02:9a:92:92'
        command: 'flip'
        args:
          - activated_face: 5
    action:
      - service: light.turn_on
        entity_id: light.main
        data:
          color_name: 'red'
  # - alias: Cube Rotate
  #   initial_state: 'on'
  #   trigger:
  #     platform: event
  #     event_type: zha_event
  #     event_data:
  #       device_ieee: '00:15:8d:00:02:9a:92:92'
  #       command: 'rotate_left'
  #   action: 
  #     - service: light.turn_on
  #       entity_id: light.main
  #       data_template:
  #         entity_id: light.main
  #         brightness: >-
  #           {% if trigger.payload_json.angle | float > 0 %}
  #           {{  states.light.main.attributes.brightness | int + 30 }}
  #           {% else %}
  #           {{  states.light.main.attributes.brightness | int - 30 }}
  #           {% endif %}
  # - alias: Cube White
  #   trigger:
  #     platform: event
  #     event_type: zha_event
  #   condition:
  #     - condition: template
  #       value_template: "{{ 'tap' == trigger.payload_json.action }}"
  #   action:
  #     - service: light.turn_on
  #       entity_id: light.main
  #       data:
  #         rgb_color: [0,0,0]
  #         white_value: 255
  - alias: Cube Yellow
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:15:8d:00:02:9a:92:92'
        command: 'flip'
        args:
          activated_face: 6
    action:
      - service: light.turn_on
        entity_id: light.main
        data:
          color_name: 'yellow'