automation:

  - alias: telegram People Departed Home Empty for 5 Minutes - ask if Roomba should start
    trigger:
      - platform: state
        entity_id: group.people
        to: 'not_home'
        for: '00:05:00'
    condition:
      - condition: state
        entity_id: input_boolean.notifications
        state: 'on'
    action:
      - service: notify.telegram
        data_template:
          message: "🗑 Should Roomba clean while the house is empty?"
          data:
            inline_keyboard:
              - 'Start Roomba:/clean, Dismiss:/dismiss'

  # Commands

  - alias: Telegram Command Roomba Start
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: '/clean@cmarty_bot'
      - platform: event
        event_type: telegram_command
        event_data:
          command: '/clean'
    action:
      - service: telegram_bot.send_message
        data_template:
          target: 
            - "{{ trigger.event.data.chat_id }}"
          message: "Roomba will begin cleaning the house now"
      - service: remote.send_command
        entity_id: remote.main
        data:
          entity_id: remote.main
          device: 59458525
          command: Clean
          num_repeats: 1
          delay_secs: 0.75
          hold_secs: 1

  # Callbacks

  - alias: Telegram Callback Roomba Start
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: '/clean'
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.message.reply_markup.inline_keyboard[0][0].text == 'Start Roomba' }}"
    action:
      - service: telegram_bot.answer_callback_query
        data_template:
          callback_query_id: "{{ trigger.event.data.id }}"
          message: "Roomba will begin cleaning the house now"
      - service: telegram_bot.edit_message
        data_template:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.chat_id }}'
          inline_keyboard:
          message: >
            {{ trigger.event.data.from_first }} (user-id:{{ trigger.event.data.user_id }}) Initiated a cleaning cycle with Roomba
      - service: remote.send_command
        entity_id: remote.main
        data:
          entity_id: remote.main
          device: 59458525
          command: Clean
          num_repeats: 1
          delay_secs: 0.75
          hold_secs: 1

  - alias: Telegram Callback Dismiss Roomba Start
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: '/dismiss'
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.message.reply_markup.inline_keyboard[0][0].text == 'Start Roomba' }}"
    action:
      - service: telegram_bot.answer_callback_query
        data_template:
          callback_query_id: '{{ trigger.event.data.id }}'
          message: 'Dismissed'
      - service: telegram_bot.edit_message
        data_template:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.chat_id }}'
          inline_keyboard:
          message: >
            {{ trigger.event.data.from_first }} (user-id:{{ trigger.event.data.user_id }}) decided not to start Roomba
