# Automations

automation:

# Time Based Automations

  - alias: Time main 1 midnight
    description: Adjust main light at midnight
    trigger:
    - at: '00:00:00'
      platform: time
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.main
          state: 'on'
    action:
    - data:
        entity_id: light.main
        color_name: red
        brightness_pct: 10
        white_value: 0
      service: light.turn_on

  - alias: Time main 2 AM
    description: Adjust main light at AM
    trigger:
    - at: '01:00:00'
      platform: time
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.main
          state: 'on'
    action:
    - data:
        entity_id: light.main
        color_name: red
        brightness_pct: 5
        white_value: 0
      service: light.turn_on

  - alias: Time main 4 dawn
    description: Adjust main light at dawn
    trigger:
      platform: numeric_state
      entity_id: sensor.front_luminance
      above: 0
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.main
          state: 'on'
        - condition: time
          after: '02:00:00'
          before: '07:00:00'
    action:
    - data:
        entity_id: light.main
        color_name: orange
        brightness_pct: 50
        white_value: 0
      service: light.turn_on

  - alias: Time main 5 morning
    description: Adjust main light at morning
    trigger:
    - at: '07:00:00'
      platform: time
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.main
          state: 'on'
    action:
    - data:
        entity_id: light.main
        color_name: yellow
        brightness_pct: 100
        white_value: 0
      service: light.turn_on

  - alias: Time main 6 morning late
    description: Adjust main ambient light at morning late
    trigger:
    - at: '08:00:00'
      platform: time
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.main
          state: 'on'
    action:
    - data:
        entity_id: light.main
        color_name: yellow
        brightness_pct: 80
        white_value: 0
      service: light.turn_on

  - alias: Time main 7 morning later
    description: Adjust main ambient light at morning later
    trigger:
    - at: '09:00:00'
      platform: time
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.main
          state: 'on'
    action:
    - data:
        entity_id: light.main
        color_name: yellow
        brightness_pct: 60
        white_value: 0
      service: light.turn_on

  - alias: Time main 8 day
    description: Adjust main light at day
    trigger:
    - at: '09:30:00'
      platform: time
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.main
          state: 'on'
    action:
    - data:
        entity_id: light.main
        color_name: yellow
        brightness_pct: 40
        white_value: 0
      service: light.turn_on

  - alias: Time main 8.5 off
    description: Adjust main ambient light at night
    trigger:
    - at: '10:00:00'
      platform: time
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.main
          state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.main
      - service: input_select.select_option
        entity_id: input_select.main_effect
        data:
          entity_id: input_select.main_effect
          option: "none"

  - alias: Time main 11 night
    description: Adjust main ambient light at night
    trigger:
    - at: '19:30:00'
      platform: time
    condition:
    - condition: state
      entity_id: light.main
      state: 'on'
    action:
      - service: light.turn_on
        entity_id: light.main
        data:
          color_name: orange
          brightness_pct: 90
          white_value: 122

  - alias: Time main 11.5 night2
    description: Adjust main light at night2
    trigger:
    - at: '20:30:00'
      platform: time
    condition:
    - condition: state
      entity_id: light.main
      state: 'on'
    action:
      - service: light.turn_on
        entity_id: light.main
        data:
          color_name: orange
          brightness_pct: 75
          white_value: 61

  - alias: Time main 12 late
    description: Adjust main light at night
    trigger:
    - at: '21:30:00'
      platform: time
    condition:
    - condition: state
      entity_id: light.main
      state: 'on'
    action:
      - service: light.turn_on
        entity_id: light.main
        data:
          color_name: orange
          brightness_pct: 55
          white_value: 0

  - alias: Time main 13 later
    description: Adjust main ambient light at night
    trigger:
    - at: '22:30:00'
      platform: time
    condition:
    - condition: state
      entity_id: light.main
      state: 'on'
    action:
      - service: light.turn_on
        entity_id: light.main
        data:
          color_name: red
          brightness_pct: 40
          white_value: 0

  - alias: Time main 14 almost midnight
    description: Adjust main ambient light at night
    trigger:
    - at: '23:30:00'
      platform: time
    condition:
    - condition: state
      entity_id: light.main
      state: 'on'
    action:
      - service: light.turn_on
        entity_id: light.main
        data:
          color_name: red
          brightness_pct: 25
          white_value: 0
